env:
  browser: true
  commonjs: true
  es2021: true
extends: google
parserOptions:
  ecmaVersion: latest
rules:
  linebreak-style:
    - "off"
    - "unix"

# change linebreak-style in the future if necessary