name: Code Linter

on: [push, pull_request]

jobs:
    build:
        name: Code Linter
        runs-on: ubuntu-latest

        steps:

            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Lint Code
              uses: github/super-linter@v4
              env:
                VALIDATE_ALL_CODEBASE: true
                IGNORE_GITIGNORED_FILES: true
                VALIDATE_JAVASCRIPT_ES: true
                VALIDATE_PYTHON: true
                VALIDATE_HTML: true
                VALIDATE_CSS: true
